{{- if .Values.proxyService.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-proxy
  labels:
    app: {{ .Release.Name }}
    {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    tailscale.com/hostname: {{ .Release.Name }}-proxy
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http-proxy
    {{- if .Values.socks5.enabled }}
    - port: {{ .Values.socks5.port }}
      targetPort: {{ .Values.socks5.port }}
      protocol: TCP
      name: socks5
    {{- end }}
  selector:
    app: {{ .Release.Name }}
{{- end }}
